run:
  skip-dirs:
    - bin
    - .github
    - tools

linters-settings:
  govet:
    check-shadowing: true

linters:
  enable-all: true
  disable:
    - wsl
    - exhaustivestruct
    - exhaustruct
    - exhaustive
    - godox
    - funlen
    - gomnd
    - gocognit
    - cyclop

issues:
  exclude-rules:
    - text: "shadow: declaration of \"err\""
      linters: ["govet"]
    - text: "use of `fmt.Print"
      linters: ["forbidigo"]
    - text: "is too short for the scope of its usage"
      linters: ["varnamelen"]
